### ISSUE TITLE
Pods on different nodes fail to mount a static FSx for Lustre instance

### ISSUE THREAD

**Issue by conorcurlett** [kubernetes-sigs/aws-fsx-csi-driver#120]
/kind bug

**What happened?**
After creating a static FSx for Lustre, I am able to mount it into a pod from one node. However, if I schedule the pod onto a different node, that is running a fsx-csi-node pod, it times out waiting to mount.

**What you expected to happen?**
The mount to work consistently across nodes.

**How to reproduce it (as minimally and precisely as possible)?**
In an EKS cluster with an on demand c5.4xlarge node and a p2.xlarge spot node, use a nodeselector to schedule to the on demand node, observe working state, then reschedule to the spot instance.

**Anything else we need to know?**:
The instances use the same IAM role, are in different subnets.

The cis-provisioner reports
```
I1214 01:00:34.267838       1 controller.go:902] Provisioning succeeded, removing PVC 22038550-1e0d-11ea-8f97-06c5af6bfebe from claims in progress
I1214 01:00:34.273701       1 controller.go:979] Final error received, removing PVC 22038550-1e0d-11ea-8f97-06c5af6bfebe from claims in progress
```

**Environment**
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b8860f", GitCommit:"b8860f6c40640897e52c143f1b9f011a503d6e46", GitTreeState:"clean", BuildDate:"2019-11-25T00:55:38Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Driver version:
0.2.0

**Comment by leakingtapan** [comment]
> The instances use the same IAM role, are in different subnets

FSx for lustre is only allowed to access from within the same subnet. Does it work if the worker nodes are in the same subnet?

**Comment by conorcurlett** [comment]
It does not (I artificially constructed a scenario where they were sharing subnets and saw the same condition). I had thought this might be the issue, but on investigation it appears that subnets in the same VPC have routes configured by default between them, so traffic should be able to flow? 
If the subnet restriction does in fact exist, that would make it pretty difficult to use this driver combined with spot instances and the cluster autoscaler, right? I'm imagining some orchestration logic would be required to manage subnet affinity (i.e. if a particular pod has a PVC for a FSx for Lustre storage class then only schedule onto nodes with a particular taint)?

**Comment by leakingtapan** [comment]
@conorcurlett my bad on not stating it clearly. Clarified my previous wording. 

Yes. I also tested that when a pod is rescheduled to a different subnet, it is still able to mount the volume and Pod becomes running. I suspect something else is wrong with your setup.

**Comment by leakingtapan** [comment]
/close
Feel free to reopen if the problem still happens :)
