### ISSUE TITLE
MountOptions not honored

### ISSUE THREAD

**Issue by irlevesque** [kubernetes-sigs/aws-fsx-csi-driver#127]
/kind bug

**What happened?**
Following the static provisioning example with a StorageClass containing:

```
mountOptions:
- flock
```

Results in the fsx-csi-node logging:

```
NodePublishVolume: mounting fs-02a9921e59e81b716.fsx.us-east-1.amazonaws.com@tcp:/fsx at /var/lib/kubelet/pods/fe090689-7b05-46fd-8095-3389ff3d80fa/volumes/kubernetes.io~csi/fsx-pv/mount with options []
```

And the volume is mounted without `flock`:

```
172.19.184.185@tcp:/fsx on /var/lib/kubelet/pods/fe090689-7b05-46fd-8095-3389ff3d80fa/volumes/kubernetes.io~csi/fsx-pv/mount type lustre (rw,lazystatfs)
```

**What you expected to happen?**

The mountOption attribute to be respected.

**How to reproduce it (as minimally and precisely as possible)?**

Deploy the example manifests in https://github.com/kubernetes-sigs/aws-fsx-csi-driver/tree/master/examples/kubernetes/static_provisioning

**Environment**
- Kubernetes version (use `kubectl version`): `1.15.6`
- Driver version: tried both `v0.2.0` and `latest`

**Comment by leakingtapan** [comment]
For static provisioned volume, you need to specify the mount option in `PersistentVolume` object, have you tried that?

**Comment by irlevesque** [comment]
Thanks @leakingtapan. I PR'ed a fix for the example code to reflect this requirement.
