### ISSUE TITLE
No container image chengpan/aws-fsx-csi-driver

### ISSUE THREAD

**Issue by dagrayvid** [kubernetes-sigs/aws-fsx-csi-driver#146]
/kind bug

**What happened?**
Following the installation instructions, after running `kubectl apply -k deploy/kubernetes/overlays/dev/kustomization.yaml` get lots of imagePullBackOff errors because the container chengpan/aws-fsx-csi-driver is not found

**What you expected to happen?**
Expected all resources to be created successfully.

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): Kubernetes Version: v1.17.1
- Using OpenShift 4.4
- Driver version: latest

**Comment by leakingtapan** [comment]
The dev overlay is for dev testing purpose, please do not use for production usage. If you need something for testing, please replace with your own registry
