### ISSUE TITLE
FSx driver does not support using different Persistence volumes on the same FSx instance 

### ISSUE THREAD

**Issue by aviorma** [kubernetes-sigs/aws-fsx-csi-driver#151]
/kind bug

**What happened?**
The current FSX driver does not support mounting different persistence volumes on the same FSx instance 
This is blocking us from reusing the same fsx instance on different persistence volumes 

Similar issues with EFS in the past 

https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/100
https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/105
https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/145
https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/167
https://github.com/kubernetes/kubernetes/issues/91556

**What you expected to happen?**

1. A new FSx Persistence volume should creates a dedicated folder on "/" path named with the persistence volume name

2. Each Statefulset pod-pv will be mounted on a new folder on the root tree on the FSx instance** 

**How to reproduce it (as minimally and precisely as possible)?**

1. Install Latest fsx driver on EKS
2. Create different persistence volumes from FSx storage class
3. Running `df -kh` within the container hosting the FSx mount point and see that it has the same mount point for different persistence volumes!!
**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`

- Driver version:

{
  "driverVersion": "v0.4.0-dirty",
  "gitCommit": "4cca48b4b005e50685a9117bec75d76014b8ad72",
  "buildDate": "2020-06-28T06:40:22Z",
  "goVersion": "go1.13.4",
  "compiler": "gc",
  "platform": "linux/amd64"
}

**Comment by scopej** [comment]
I've been working on some improvements to fix this.
I just submitted https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/162.

I'm working on the CLA process now, but wanted to start a dialog on the fix and if this is the kind of change the team would accept.

**Comment by wongma7** [comment]
Would it solve the statefulset use-case? I am not too familiar with statefulsets, is it possible to create a pvc template where the volumeHandle is the same but the volumeAttributes differ per pet in the set

**Comment by svella** [comment]
Add my vote. We were looking at switching from EFS for FSx for Lustre for some workloads for which EFS is completely unsuitable, but having to allocate a separate FSx with a minimum of 1.2Tib for each PV is prohibitively expensive.

**Comment by AshishisAws** [comment]
Any updates on this
