### ISSUE TITLE
FSx CSI Driver Crashing When Deployed to Amazon EKS cluster

### ISSUE THREAD

**Issue by gkao123** [kubernetes-sigs/aws-fsx-csi-driver#153]
/kind bug

**What happened?**
When I deploy the FSx CSI driver following the instructions in https://docs.aws.amazon.com/eks/latest/userguide/fsx-csi.html, the the FSx driver is crashing:

```
a483e701f5be:~ geoffkao$ kubectl get pods -n kube-system
NAME                                 READY   STATUS             RESTARTS   AGE
coredns-8f4f54dc-9wnst               1/1     Running            0          98m
coredns-8f4f54dc-zvcp7               1/1     Running            0          98m
fsx-csi-controller-9f6f6846c-l98lz   1/2     CrashLoopBackOff   18         73m
fsx-csi-controller-9f6f6846c-ptxf6   1/2     CrashLoopBackOff   18         73m`
```

**What you expected to happen?**

I expect the controller to have a status of running.

**How to reproduce it (as minimally and precisely as possible)?**

Follow the instructions in the AWS FSx CSI documentation. In step 8 where the guide instructs the user to confirm the filesystem is provisioned, the pvc status will be stuck in pending indefinitely. Here, you can verify the driver is crashing. 

**Anything else we need to know?**:
Logs on the pod the driver is deployed to ->

```
a483e701f5be:~ geoffkao$ kubectl -n kube-system logs -p fsx-csi-controller-9f6f6846c-l98lz
error: a container name must be specified for pod fsx-csi-controller-9f6f6846c-l98lz, choose one of: [fsx-plugin csi-provisioner]
a483e701f5be:~ geoffkao$ kubectl -n kube-system logs -p fsx-csi-controller-9f6f6846c-l98lz -c csi-provisioner
Error from server (BadRequest): previous terminated container "csi-provisioner" in pod "fsx-csi-controller-9f6f6846c-l98lz" not found
a483e701f5be:~ geoffkao$ kubectl -n kube-system logs -p fsx-csi-controller-9f6f6846c-l98lz -c fsx-plugin
F0827 14:47:43.678032       1 driver.go:58] EC2 instance metadata is not available
a483e701f5be:~ geoffkao$ 
```

**Environment**
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T19:00:19Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Driver version:

The driver that is deployed when 
`kubectl apply -k "github.com/kubernetes-sigs/aws-fsx-csi-driver/deploy/kubernetes/overlays/stable/?ref=master"
`
is ran.

**Comment by wongma7** [comment]
"EC2 instance metadata is not available" is a fatal error, any idea why the metadata service is not available on the node fsx-csi-controller-9f6f6846c-l98lz is running on?

**Comment by gkao123** [comment]
I'm not sure. Could this be a VPC/subnet/security group issue?

**Comment by wongma7** [comment]
No I do not think so. What does it show for MetadataOptions when you describeinstances the node instance

**Comment by gkao123** [comment]
Where can I find the node instance information?

**Comment by jqmichael** [comment]
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html#configuring-instance-metadata-options

**Comment by gkao123** [comment]
Deploying the driver to a self-managed cluster run on EC2 nodes works (**Section** Managed Nodes - Linux on https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html)

Originally, the driver was deployed to a Fargate managed cluster (**Section** AWS Fargate - Linux on https://docs.aws.amazon.com/eks/latest/userguide/getting-started-eksctl.html)

**Comment by shiba24** [comment]
Hello, thank you for the report, I've encountered the issue too - what can i do to fix for the Fargate-managed cluster?

**Comment by manpreetsnehra** [comment]
This might be because of enabling metadata v2 and disabling metadata v1 as required by AWS security CIS rules.

**Comment by tsunamishaun** [comment]
This indeed does happen when IMDSv1 is disabled in favor of V2.  Two things need to happen in order to fix. Pods need access to IMDSv2 through hostNetwork (chart setting that doesnt exist yet) and that can use IMDSv2 (grab a token before calling the api).  That is in essence what is needed here, this issue should be re-opened.

**Comment by elgalu** [comment]
Why does it need access to EC2 metadata? can the driver work without that?
