### ISSUE TITLE
Images can be pulled from aws ecr repository

### ISSUE THREAD

**Issue by gietschess** [kubernetes-sigs/aws-fsx-csi-driver#167]
**Is your feature request related to a problem? Please describe.**
I'd like to pull the images used by the fsx-csi-driver directly from the aws ecr repository instead of docker hub or quay.io, like it's already possible for the other csi-drivers (ebs and efs).

**Describe the solution you'd like in detail**
Build images are also pushed to the aws repositories (602401143452.dkr.ecr.$AWS_REGION.amazonaws.com)

**Describe alternatives you've considered**
Due to the docker download rate limits i've got to pull and push all these images to my own registry.

**Comment by gietschess** [comment]
It seems, that the images are already available in the repositories of the us-west-2 region but not in all regions, e.g. eu-central-1.

**Comment by wongma7** [comment]
/lifecycle frozen

sorry about this taking so long, but yeah, in light of the docker hub throttling definitely want to move off there. EBS has gcr and ecr, efs has ecr, fsx is lacking both.

**Comment by bkrugerp99** [comment]
Any word on this one?

**Comment by jacobwolfaws** [comment]
There's a PR up to address this: https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/285

**Comment by jacobwolfaws** [comment]
This has been fully implemented, closing this. If there are any issues with the public repo please let us know!
/close
