### ISSUE TITLE
Change the installation step guide in the docs

### ISSUE THREAD

**Issue by ElAntagonista** [kubernetes-sigs/aws-fsx-csi-driver#168]
**Is your feature request related to a problem?/Why is this needed**
The documentation for this project suggests two ways of installing the driver: `helm chart` and `kubectl apply`.
The `kubectl` example points to the dev overlay which turns out to be wildly unstable and results in an unnecessary time spent troubleshooting.

/feature

**Describe the solution you'd like in detail**
The installation instruction example for `kubectl apply` should point to the stable overlay or it should be explicitly noted that this is a dev overlay and as such is very unstable.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by wongma7** [comment]
Sorry about this, there's https://github.com/kubernetes-sigs/aws-fsx-csi-driver/pull/170 open to fix it , working on merging it.
