### ISSUE TITLE
Add a tolerations field to the helm chart for the daemonset

### ISSUE THREAD

**Issue by dmildh** [kubernetes-sigs/aws-fsx-csi-driver#190]
In order to support running the daemonset on all nodes in a cluster it would be nice if a tolerations var could be added to the node.yaml for the helm chart so that you don't have to due something like this.

`kubectl patch ds aws-fsx-csi-driver-daemonset --patch '{"spec": {"template": { "spec": {"tolerations": [{"operator": "Exists"}]}}}}'`

**Comment by wongma7** [comment]
It has been added by helm chart 1.0 which has a number of breaking changes https://github.com/kubernetes-sigs/aws-fsx-csi-driver#upgrading-from-version-0x-to-1x-of-the-helm-chart
