### ISSUE TITLE
New Chart Versions Not Being Published

### ISSUE THREAD

**Issue by toneill818** [kubernetes-sigs/aws-fsx-csi-driver#195]
/kind bug

**What happened?**
When adding the helm repo `helm repo add aws-fsx-csi-driver1 https://kubernetes-sigs.github.io/aws-fsx-csi-driver/` only version 0.1.0 is available. The latest version seems to be 0.3.0.

`helm search repo aws-fsx-csi-driver --version 0.3.0`
`No results found`

**What you expected to happen?**
When the chart is updated, the repo should hold the new chart version.

**How to reproduce it (as minimally and precisely as possible)?**
Add the repo
`helm repo add aws-fsx-csi-driver1 https://kubernetes-sigs.github.io/aws-fsx-csi-driver/` 

Search for the version
`helm search repo aws-fsx-csi-driver --version 0.3.0`

**Comment by wongma7** [comment]
1.0.0 which refers to driver version 0.4.0 just got published. It does have many breaking changes so check before upgrading https://github.com/kubernetes-sigs/aws-fsx-csi-driver#upgrading-from-version-0x-to-1x-of-the-helm-chart
