### ISSUE TITLE
Unable to attach or mount volumes

### ISSUE THREAD

**Issue by dlmestre** [kubernetes-sigs/aws-fsx-csi-driver#213]
/kind bug

**What happened?**
The pod **fsx-app** remains in ContainerCreating Status. When we run the command _describe pod_ we see the following warnings:
 
- AttachVolume.Attach failed for volume "fsx-pv" : Attach timeout for volume fs-.....
- Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[persistent-storage kube-api-access-b4tct]: timed out waiting for the condition

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**
Go through the steps in [static provisioning](url https://github.com/kubernetes-sigs/aws-fsx-csi-driver/tree/master/examples/kubernetes/static_provisioning)

**Anything else we need to know?**:

**Environment**
- Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
- Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
-  Luster Version : 2.12

**Comment by jacobwolfaws** [comment]
@dlmestre Hi, are you still having this issue?

**Comment by jacobwolfaws** [comment]
feel free to open a new issue if this comes up again @dlmestre.
/close
