### ISSUE TITLE
OpenZFS support

### ISSUE THREAD

**Issue by oberstet** [kubernetes-sigs/aws-fsx-csi-driver#242]
**Is your feature request related to a problem?/Why is this needed**

Amazon FSx is available on top of different backing filesystems:

> You can choose between four widely-used file systems: NetApp ONTAP, OpenZFS, Windows File Server, and Lustre.

I would love to use a Amazon FSx for OpenZFS CSI Driver. I don't know if this is outside the scope of the CSI dirver here, for one, because it is "generically named" ("https://github.com/kubernetes-sigs/aws-fsx-csi-driver"). I read the docs, and I also tried to contact developers/anyone via Slack, but got no reply. Hence I am using an issue here to try to find out. If this is wrong, out of scope, I just go elsewhere, please let me know where/how.

/feature

**Describe the solution you'd like in detail**

Support OpenZFS in addition to Lustre as a backing filesystem in this CSI driver.

**Describe alternatives you've considered**

Using Lustre. However, for my use case (mostly database stuff), ZFS is a better fit. I would not run a production database (eg PostgreSQL) on Lustre. So this means, fall back to an AWS EBS backed CSI driver, and not be able to use stuff like complete Merkle tree based data verification, snapshots, send/receive, ...

**Comment by 11qu1d** [comment]
Is this still an issue? According to aws docs this driver should support it. https://docs.aws.amazon.com/fsx/latest/OpenZFSGuide/openzfs-integrations.html

**Comment by SohumB** [comment]
The NFS driver works as lowest common denominator access to the zfs filesystem, yes, but fsx/zfs would be capable of stronger integration with the CSI API. For instance, we would be very interested in support for the snapshotting api, as backed by zfs snapshots.

**Comment by jacobwolfaws** [comment]
/lifecycle frozen

Hi @oberstet 
This CSI driver is specifically the FSx for Lustre CSI Driver, so OpenZFS support would be in a separate repository. We generally don't comment on the future direction of products and features, but I've brought this up with the OpenZFS team as we are always interested in the different use cases our users target.

**Comment by oberstet** [comment]
@jacobwolfaws thanks! yeah, I was aware the issue is actually wrong here, but which other repo to stick it on? so I thought, still best to post here to leave a mark at least. it worked - well, a bit;) I'm a big ZFS fan, and "Amazon FSx for OpenZFS " would rock ... so thanks again for forwarding!

**Comment by jacobwolfaws** [comment]
The beta release for the FSx for OpenZFS CSI Driver is now live! https://github.com/kubernetes-sigs/aws-fsx-openzfs-csi-driver. Going to leave this up until aws documentation is updated

**Comment by jacobwolfaws** [comment]
The OpenZFS CSI Driver is officially live! https://aws.amazon.com/about-aws/whats-new/2023/06/csi-driver-amazon-fsx-openzfs/ Closing this issue
/close

**Comment by oberstet** [comment]
fantastic!! k8 containers directly from zfs. love it=)
