### ISSUE TITLE
[AWS-FSX] Pod is hanging at terminating when evicting pods for scaling down  

### ISSUE THREAD

**Issue by jinleileiking** [kubernetes-sigs/aws-fsx-csi-driver#253]
/kind bug

 https://github.com/kubernetes-sigs/aws-fsx-csi-driver/blob/master/deploy/kubernetes/base/node-daemonset.yaml 

should add annotation to not evict by default.

see https://github.com/kubernetes/autoscaler/issues/4966

**Comment by jacobwolfaws** [comment]
hi @jinleileiking are you still experiencing this issue? If so, can you be a bit more clear about what change you're proposing and/or make a PR with the proposed change. Thanks!
