### ISSUE TITLE
AlreadyExists desc = There is already a disk with same ID and different size

### ISSUE THREAD

**Issue by AndriySidliarskiy** [kubernetes-sigs/aws-fsx-csi-driver#287]
/kind bug

**What happened?**
AlreadyExists desc = There is already a disk with the same ID and different size
**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**
When create SCRATCH_2 pvc with s3 import and output paths

Used this configuration: 

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fsx-sc-s3
provisioner: fsx.csi.aws.com
reclaimPolicy: Delete
parameters:
  autoImportPolicy: NEW_CHANGED_DELETED
  fileSystemTypeVersion: '2.12'
  perUnitStorageThroughput: '200'
  s3ImportPath: s3://
  s3ExportPath: s3://
  deploymentType: SCRATCH_2
  securityGroupIds: sg-
  subnetId: subnet-
  extraTags: "VolumeName=test"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-lustre-s3-mount-gfgftf
  namespace: default
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: fsx-sc-s3
  resources:
    requests:
      storage: 1400Gi
      
**Anything else we need to know?**:
Also previously create storage class but with persistent 1 type 
**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by jacobwolfaws** [comment]
Hi @AndriySidliarskiy 
Some questions so that I can better help you debug this issue.
1. Can you share the full error message & output
2. Did you create a Kubernetes service account for the driver and attach the AmazonFSxFullAccess AWS-managed policy to the service account?
3.

**Comment by jacobwolfaws** [comment]
Hi @AndriySidliarskiy,
I have some questions that I hope can help us debug this issue.
1. Can you share the full output that includes the error message?
2. Did you follow the instructions here: https://docs.aws.amazon.com/eks/latest/userguide/fsx-csi.html for setting up and using the csi driver (specifically step 3 where you create a Kubernetes service account for the driver and attach the AmazonFSxFullAccess AWS-managed policy to the service account)?
3. Can you share your driver's permissions policies?

**Comment by AndriySidliarskiy** [comment]
@jacobwolfaws I fixed It is a problem when you provide perUnitStorageThroughput parameter for SCRATCH_2 or SCRATCH_1 in the storage class you have this error in logs, so maybe you create advanced templates for login for this storage class.

**Comment by jacobwolfaws** [comment]
Ah yes, that would cause issues, sorry for not catching that! Will open a new issue for adding more descriptive error messaging in this case. 
/close
