### ISSUE TITLE
Add descriptive error message when trying to specify throughput for scratch fs

### ISSUE THREAD

**Issue by jacobwolfaws** [kubernetes-sigs/aws-fsx-csi-driver#288]
/kind bug

**What happened?**
https://github.com/kubernetes-sigs/aws-fsx-csi-driver/issues/287
Developer tried to specify throughput for a SCRATCH filesystem and got a nondescriptive error.

**What you expected to happen?**
Ideally we would have an error message that says something along the lines of "Can't specify throughput for SCRATCH filesystems"

**How to reproduce it (as minimally and precisely as possible)?**
see https://github.com/kubernetes-sigs/aws-fsx-csi-driver/issues/287
**Anything else we need to know?**:

**Environment**
Shouldn't be relevant here

**Comment by RyanDevlin** [comment]
My team and I just encountered this problem and had to comb through the source code to debug it ([it occurs here btw](https://github.com/kubernetes-sigs/aws-fsx-csi-driver/blob/v0.9.0/pkg/cloud/cloud.go#L228)). I went to open an issue but found this already is requested. +1 for this being fixed soon, it's very confusing.

**Comment by jacobwolfaws** [comment]
^ PR addresses the issue and it will be merged in the next release. Thanks!
