### ISSUE TITLE
Propagate PVC labels as AWS tags in file systems/volumes

### ISSUE THREAD

**Issue by kanor1306** [kubernetes-sigs/aws-fsx-csi-driver#303]
**Is your feature request related to a problem? Please describe.**
My feature request is related with easier monitoring and cost reporting when using dynamic provisioning. I think a common use case for Lustre FSx is having short lived (i.e. a few hours) very performant volumes that are used as storage for jobs.

Lets say that I run a job, and then I want to add a grafana board with information about the job, and part of it is information about the storage I requested. My normal approach if would be to label the PVC with something that helps me link my job with the PVC (and PV). In the case of FSx, what I would like is to label a PVC that used the FSx storage class, and that the labels (or some of them) will also be set as tags of the file system in AWS. Currently, this is not possible with the FSx driver, as the only tagging possible is via Storage Class, making it (if I understand it properly) not dynamic.

This lack of tagging, makes cumbersome to link a workload in Kubernetes with a AWS FSx file system. In the case of Grafana, this can be achieved with some complex query, as you can indirectly link a PVC with its FSx file system via the CSIVolumeName tag (that seems to be the only one automatically created), but it is cumbersome and requires a complex query that is also not very efficient. What is even more difficult is cost monitoring. Ideally I would like to just be able to filter in my cost explorer with a Tag, so I can know the FSx costs for a specific workload.

**Describe the solution you'd like in detail**
Selected labels of a PVC are set as AWS Tags in FSx file systems and volumes

**Describe alternatives you've considered**
Some job that does the tagging, but it seems that is a functionality that could make sense to have in the driver

**Comment by jacobwolfaws** [comment]
Hi @kanor1306, looking at where the [CreateVolumeRequest is made + where capacity is pulled from the claim through a v1 api call](https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L630#L646) I'm not sure how feasible this added feature would be. Do you have an example of this being implemented anywhere else?

**Comment by kanor1306** [comment]
@jacobwolfaws actually I thought that it was a common thing to have, but turns out that it is not. I have looked into it a bit more and run into this thread of the EBS driver, https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/180 where they discuss this same thing. In the case of the EBS driver they have slightly more flexibility, as they allows some metadata (see https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/tagging.md#storageclass-tagging), but in any case is not enough for my use case. 

As you have pointed out this goes down to the external-provisioner, so not much to be done, Thanks for your help!

**Comment by kanor1306** [comment]
For reference, the discussion about this issue in the external provisioner repo. The original post is about annotations but I think that most of the concerns apply to labels too: https://github.com/kubernetes-csi/external-provisioner/issues/86

**Comment by jacobwolfaws** [comment]
Thanks @kanor1306 for looking into this more.

For future readers: This seems to be the solution used in the EBS CSI Driver: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/180#issuecomment-861829873 . I'm not sure if the metadata would propagate to the tags similarly with the lustre csi driver but it's worth exploring. I'll share the results once I test it.
