### ISSUE TITLE
fsx-csi-controller container failing to start with error message "flag provided but not defined: -mode"

### ISSUE THREAD

**Issue by CraigRubendall** [kubernetes-sigs/aws-fsx-csi-driver#315]
/kind bug

**What happened?**

I've followed the directions for installing the FSx Lustre CSI.  

When the fsx-csi-node daemonset starts pods, they fail to start and I'm getting the following error message:

 kubectl logs fsx-csi-controller-f95c5577b-s84jk -n kube-system -c fsx-plugin
**flag provided but not defined: -mode**
Usage of /bin/aws-fsx-csi-driver:
  -add_dir_header
        If true, adds the file directory to the header of the log messages
  -alsologtostderr
        log to standard error as well as files
  -endpoint string
        CSI Endpoint (default "unix://tmp/csi.sock")
  -log_backtrace_at value
        when logging hits line file:N, emit a stack trace
  -log_dir string
        If non-empty, write log files in this directory
  -log_file string
        If non-empty, use this log file
  -log_file_max_size uint
        Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
  -logtostderr
        log to standard error instead of files (default true)
  -one_output
        If true, only write logs to their native severity level (vs also writing to each lower severity level)
  -skip_headers
        If true, avoid header prefixes in the log messages
  -skip_log_headers
        If true, avoid headers when opening log files
  -stderrthreshold value
        logs at or above this threshold go to stderr (default 2)
  -v value
        number for the log level verbosity
  -version
        Print the version and exit
  -vmodule value
        comma-separated list of pattern=N settings for file-filtered logging

Note that I have seen this work previously

**What you expected to happen?**

the pods for the deployment and daemonsets would start and run properly.

**How to reproduce it (as minimally and precisely as possible)?**

I've attached the yaml file I'm using to create the resources on the cluster.
Before doing this, I created a secret aws-secret in kube-system namespace containing the aws credentials for an account.

**Anything else we need to know?**:

I've seen this work in the past, so I'm not sure if something has changed in the recent releases (I tried 0.8 and 0.9 with the same result).

Maybe I'm missing a step on my side that I did before but I can't see what I may have missed that would cause such an error as bad parameter.

**Environment**
- Kubernetes version (use `kubectl version`):

kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.17", GitCommit:"953be8927218ec8067e1af2641e540238ffd7576", GitTreeState:"clean", BuildDate:"2023-02-22T13:34:27Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-0a21954", GitCommit:"cd5c12c51b0899612375453f7a7c2e7b6563f5e9", GitTreeState:"clean", BuildDate:"2023-04-15T00:32:27Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}

- Driver version:

0.9

**Comment by jacobwolfaws** [comment]
Hi @CraigRubendall it seems like you're pulling the helm chart from the master branch of our repo, not from the latest tagged helm version (1.5.1). We're releasing a substantial change with the new csi driver that involved changing the helm configuration as well, which is why you're seeing this mismatch (mode is being set in helm but isn't used in the v0.9.0 csi driver). We recommend using the latest tagged helm chart/the chart from that commit.

Also, we're releasing a new csi driver + helm chart today, so I would expect this issue to resolve since the new csi driver image will be inline with main.

**Comment by jacobwolfaws** [comment]
I'll close this PR once the CSI driver is fully released

**Comment by jacobwolfaws** [comment]
released new CSI driver + helm chart, closing this
