### ISSUE TITLE
Allow mounting two different subdirectories on the same pod

### ISSUE THREAD

**Issue by colearendt** [kubernetes-sigs/aws-fsx-csi-driver#328]
/kind bug

**What happened?**

Mounting two different subdirectories (`/one` and `/two`) of the same lustre filesystem onto the same pod fails, never resolves.

**What you expected to happen?**

Mounting two different subdirectories of the same lustre filesystem should succeed (without making other directories, e.g. `/three` and `/four`, available)

**How to reproduce it (as minimally and precisely as possible)?**

- Create two PVs referencing the same Lustre filesystem at different subdirectories
- Create two PVCs referencing these PVs
- Create two volumes / volumeMounts on the same pod that reference these PVCs and mount at different locations
- Notice that `ContainerCreating` never succeeds

```
  Type     Reason       Age    From     Message
  ----     ------       ----   ----     -------
  Warning  FailedMount  2m36s  kubelet  Unable to attach or mount volumes: unmounted volumes=[storage2], unattached volumes=[storage3 kube-api-access-8tsdh storage2]: timed out waiting for the condition
  Warning  FailedMount  20s    kubelet  Unable to attach or mount volumes: unmounted volumes=[storage2], unattached volumes=[storage2 storage3 kube-api-access-8tsdh]: timed out waiting for the condition
```

**Anything else we need to know?**:

Related to #247 

**Environment**
- Kubernetes version (use `kubectl version`):
- Driver version:

**Comment by DevSusu** [comment]
+1 for the issue

Since Lustre storage can only be provisioned in unit of `1200GiBs`, it is important that the volume can be distributed across namespaces, which needs multiple static PVs in 1 FSx volume.

**Comment by jacobwolfaws** [comment]
@colearendt just following up on this

**Comment by colearendt** [comment]
Woops. Thanks for the follow up! I’ll give reproducing with more details a shot next week!

**Comment by jacobwolfaws** [comment]
Going to close out this issue since I wasn't able to repro and it doesn't seem like it's continuing to have impact, feel free to reopen with more details and/or this continues causing issues. Thanks!
/close
