### ISSUE TITLE
Adopt Kubernetes recommended label for `app`

### ISSUE THREAD

**Issue by thetric** [kubernetes-sigs/aws-fsx-csi-driver#330]
/kind bug

**What happened?**
The Helm chart is deployed with the resources labelled with `app` instead of the [Kubernetes recommended label](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) `app.kubernetes.io/name`.

**What you expected to happen?**

The Helm chart makes use of the recommended label.

**How to reproduce it (as minimally and precisely as possible)?**

Deploy it.

**Anything else we need to know?**:

This may possibly be a breaking change as it might require a re-installation of the Helm chart because the `selector` `matchLabels` will change.

Same issue in the External snapshotter driver: https://github.com/kubernetes-csi/external-snapshotter/issues/843

**Environment**
- Kubernetes version (use `kubectl version`): 1.27
- Driver version: 0.10.0

**Please also attach debug logs to help us better diagnose**

n/a

**Comment by jacobwolfaws** [comment]
Hi @thetric thanks for opening this issue, I see that you linked the external-snapshotter and not the ebs-csi-driver, are you planning on opening a separate issue with the [ebs driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver)? 

> This may possibly be a breaking change as it might require a re-installation of the Helm chart because the selector matchLabels will change.

This is important to note— we'll need to make sure to document this possibility once this change is made. If all the aws csi drivers need to make this change it should probably be a coordinated update.

**Comment by thetric** [comment]
> I see that you linked the external-snapshotter and not the ebs-csi-driver, are you planning on opening a separate issue with the [ebs driver](https://github.com/kubernetes-sigs/aws-ebs-csi-driver)?

Nice catch, I have corrected the issue description and opened an issue in the ebs driver repo.

On a first glance this looks like almost all Helm charts in this GitHub project are affected. I'm not quite sure how to communicate this without creating dozens of issues and separate discussions?
