### ISSUE TITLE
OpenShift / AWS ROSA setup/support

### ISSUE THREAD

**Issue by jsanchezmartinez** [kubernetes-sigs/aws-fsx-csi-driver#350]
Hi,
Due to there is no official S3 CSI, we would like to use FSx CSI for Lustre (with S3 backend) in OpenShift / ROSA.
Would it be possible to provide setup for the platform?
Regards,

**Comment by deva2023** [comment]
> Hi, Due to there is no official S3 CSI, we would like to use FSx CSI for Lustre (with S3 backend) in OpenShift / ROSA. Would it be possible to provide setup for the platform? Regards,

Hi, please follow this [link](https://github.com/awslabs/mountpoint-s3/issues/150)  for updates on the enhancement request for a CSI driver for S3
