### ISSUE TITLE
EKS 1.28(BottleRocketOS) Does not Support Lustre

### ISSUE THREAD

**Issue by kamirendawkins** [kubernetes-sigs/aws-fsx-csi-driver#356]
/kind bug

**What happened?**
EKS 1.28+ with BottleRocket Instances do not support FSX-Lustre

Appears quite related: https://github.com/bottlerocket-os/bottlerocket/issues/3459

Pods will hang in container creating with the following error:

```
/mount failed: No such device
Are the lustre modules loaded?
Check /etc/modprobe.conf and /proc/filesystems
```

**What you expected to happen?**
Volumes to mount correctly.

**How to reproduce it (as minimally and precisely as possible)?**

Upgrade an existing cluster with existing FSX-Lustre PVCs while using BottleRocket AMIs.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): ESK 1.28.1
- Driver version: v1.0.0(Helm Chart v1.7.0)

**Comment by jacobwolfaws** [comment]
Hi @kamirendawkins, we plan to release AL2023 support by end of Q1 2024. There's a related issue open with amazonlinux:
https://github.com/amazonlinux/amazon-linux-2023/issues/309

**Comment by kamirendawkins** [comment]
@jacobwolfaws Any chance there are also plans that align to this for BottleRocket?

**Comment by jacobwolfaws** [comment]
That's something the BottleRocket team would need to answer. Once we've released AL2023 Lustre client support, I'll provide an update in the BottleRocket issue and close this side

**Comment by larvacea** [comment]
FSx Lustre is supported in our later variants (such as EKS 1.28 and ECS 2) starting with [v1.19.3](https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.19.3). I have tested both native mounts and the CSI driver. Thanks for asking!

**Comment by jacobwolfaws** [comment]
Thanks @larvacea!

/close
