### ISSUE TITLE
Use pre-existing fsx lustre filesystem in storageclass

### ISSUE THREAD

**Issue by paramjeet01** [kubernetes-sigs/aws-fsx-csi-driver#358]
**Is your feature request related to a problem? Please describe.**

I currently possess a 10TB filesystem and I desire to attain a throughput of 10GB/s, using 1000MB/s per TiB of persistent SSD storage. I've already provisioned this storage using Terraform. Now, I'd like to employ a storage class to leverage the existing filesystem, rather than dynamically provisioning it, as this approach restricts the anticipated throughput.

**Describe the solution you'd like in detail**

I like to use the pre-existing Fsx lustre filesystem using the storageclass object than dynamically provisioning the filesystem.

**Describe alternatives you've considered**

Create PV with retain/recycle option than use it , once the pod releases the claim.

**Additional context**

- Add feature to use existing fsx lusture filesystem.

**Comment by jacobwolfaws** [comment]
@paramjeet01 Static provisioning is a very common use case for the FSx for Lustre CSI Driver. Please look see the example here: https://github.com/kubernetes-sigs/aws-fsx-csi-driver/tree/master/examples/kubernetes/static_provisioning

**Comment by jacobwolfaws** [comment]
Hi @paramjeet01, Static provisioning, where the csi driver mounts an existing filesystem, is a common use case for the csi driver. We have an example of static provisioning in the repo: https://github.com/kubernetes-sigs/aws-fsx-csi-driver/tree/master/examples/kubernetes/static_provisioning.
