### ISSUE TITLE
Unable to create files in the fsx

### ISSUE THREAD

**Issue by paramjeet01** [kubernetes-sigs/aws-fsx-csi-driver#359]
/kind bug

**What happened?**
I have mounted the fsx to pod via csi driver , when i try to create file it throws 'Invalid argument'

**What you expected to happen?**
- To create files inside the pod when fsx is mounted to the pod.

**How to reproduce it (as minimally and precisely as possible)?**
- Install fsx-csi-driver via helm
- Create PV ,PVC and attach PVC to the pod. 

**Environment**
- Kubernetes version : v1.17.12
- Driver version: v1.0.0
- Kernel version: 4.9.0-19-amd64

**Comment by paramjeet01** [comment]
Is it mandatory to have lustre client in all nodes before installing csi driver ?

**Comment by jacobwolfaws** [comment]
The lustre client kernel modules are baked into the AL2 AMI, so no additional work needs to be done to manage the lustre client at the node-level

**Comment by jacobwolfaws** [comment]
Hi @paramjeet01 are you still having this issue? Could you share the logs from your application pod and node csi pods?
