### ISSUE TITLE
FSx Lustre Nodes failing to mount

### ISSUE THREAD

**Issue by shahmonanshi** [kubernetes-sigs/aws-fsx-csi-driver#366]
/kind bug

**What happened?**
Every ~24 hours, I am encountering an corrupted fsx-csi node. This is causing PV mounting issues. 

`"MountVolume.SetUp failed for volume "lustre-fsx-storage-rsw-pv" : kubernetes.io/csi: mounter.SetUpAt failed to check for STAGE_UNSTAGE_VOLUME capability: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins/fsx.csi.aws.com/csi.sock: connect: connection refused""`

**What you expected to happen?**
Pods are able to mount the volume. 

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:
The current workaround was to set up a cronjob that reaps/rolls over the fsx nodes daily. 

**Environment**
- Kubernetes version (use `kubectl version`): 1.27
- Driver version: 1.7.0

**Comment by colearendt** [comment]
Potentially related to #244

**Comment by jacobwolfaws** [comment]
Hi @shahmonanshi, can you set logLevel to 5 for your fsx-plugin and then next time this happens, prior to deleting the node, can you run these commands on the node to collect additional logging:
```
curl -O https://raw.githubusercontent.com/awslabs/amazon-eks-ami/master/log-collector-script/linux/eks-log-collector.sh
sudo bash eks-log-collector.sh
```

**Comment by shahmonanshi** [comment]
Hi @jacobwolfaws, I am deleting/creating the nodes and creating new ones. I will enable debug logging and share some more details once I run into this problem again :)
