### ISSUE TITLE
Add Affinity to DaemonSet

### ISSUE THREAD

**Issue by karaktaka** [kubernetes-sigs/aws-fsx-csi-driver#376]
**Is your feature request related to a problem? Please describe.**
If using the chart in a cluster with fargate enabled and several nodes with different taints, the daemonset tries to deploy the fsx-plugin also to those fargate nodes, which is not possible. 

**Describe the solution you'd like in detail**
Adding a configurable affinity definition to the helm chart would enable one to specify an antiaffinity for fargate

**Comment by KenFigueiredo** [comment]
@karaktaka Is there a release/tag planned that will contain this helm chart update?
