### ISSUE TITLE
Create New Helm Chart Release

### ISSUE THREAD

**Issue by toneill818** [kubernetes-sigs/aws-fsx-csi-driver#386]
**Is your feature request related to a problem? Please describe.**
Create a new version of the helm chart that includes the updates since 2.9.0

**Describe the solution you'd like in detail**
Chart version 2.9.1 gets created

**Describe alternatives you've considered**
Downloading the source code and pointing helm to the currently installed

**Comment by jacobwolfaws** [comment]
Might be easiest to just cut 2.9.2, job for 2.9.1 broken since it's using the old releaser: https://github.com/kubernetes-sigs/aws-fsx-csi-driver/actions/runs/10599639792/workflow
