### ISSUE TITLE
FSx Is Created In Version 2.10 Instead of 2.15

### ISSUE THREAD

**Issue by vitaly-dt** [kubernetes-sigs/aws-fsx-csi-driver#399]
/kind bug

**What happened?**
FSx is providing the file system in version 2.10

**What you expected to happen?**
FSx is providing the file system in version 2.15

**How to reproduce it (as minimally and precisely as possible)?**
Use the dynamic provisioning example with S3

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.30
- Driver version: 1.9

**Comment by jacobwolfaws** [comment]
You can specify the FileSystemTypeVersion as shown in the example storageclass.yaml: https://github.com/kubernetes-sigs/aws-fsx-csi-driver/blob/master/examples/kubernetes/dynamic_provisioning/specs/storageclass.yaml#L16
