### ISSUE TITLE
Grants controller necessary permissions through policy file

### ISSUE THREAD

**Issue by Jeffwan** [kubernetes-sigs/aws-fsx-csi-driver#42]
As a customer, I'd like to use policy file and grant permission to node groups rather than using `aws_access_key_id` and `aws_secret_access_key`.  It's hard for me to provide fine grain control for it because documentation doesn't state minimum permissions CSI driver needs and I have to provide admin access to avoid permission errors and failures. 

Solution: 
I would suggest to explicitly list permissions in a policy file and then attach to node group. 

/feature

**Comment by christopherhein** [comment]
Once we have the permissions necessary we can add it to `eksctl` like the EBS CSI - https://github.com/weaveworks/eksctl/pull/652
