### ISSUE TITLE
No data available when opening a file in lustre

### ISSUE THREAD

**Issue by hamedhsn** [kubernetes-sigs/aws-fsx-csi-driver#63]
/kind bug

**What happened?**
We have created the file system manually and using the static provisioning to create pvc. It gets mounted successfully and I can list the files in fsx.
`-rwxr-xr-x 1 root root 2.6K Apr 11 14:43 romain_manual_fix.csv`

However, when I cat a file to see the content I get `No data available`. when I open it in an editor it is empty.

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-07-10T10:13:58Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.8-eks-7c34c0", GitCommit:"7c34c0d2f2d0f11f397d55a46945193a0e22d8f3", GitTreeState:"clean", BuildDate:"2019-03-01T22:49:39Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Driver version:

**Comment by leakingtapan** [comment]
@hamedhsn do is the file created? Is it sourced from S3 using FSx for Lustre data repository? Or it is created by your application container?

**Comment by hamedhsn** [comment]
The files are already created and exists in s3 and am creating the lustre
by passing the s3 path.
When trying to look at them inside my container, get the error message.

**Comment by leakingtapan** [comment]
Is your issue reproducible ? If yes, what are the steps? I test the FSx for Lustre with S3 again and it works with cat command. The example used is example/dynamic_provisioning_s3.

**Comment by hamedhsn** [comment]
we are using static provisioning under example folder. Can you test that?

>

**Comment by leakingtapan** [comment]
Tested static provisioning, it works for me as well. Created a file named coc.md in s3 and a fsx lustre to point to the bucket.

```
>> kk exec -ti fsx-app -- cat /data/coc.md
**Kubernetes Community Code of Conduct**

Kubernetes follows the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md)
```

**Comment by leakingtapan** [comment]
@hamedhsn do you see have the problem?

**Comment by hamedhsn** [comment]
@leakingtapan I think the problem is from our side(AWS) because we get the same error when we attach it to EC2 instance. we are investigating with AWS.
@emalihin FYI

**Comment by leakingtapan** [comment]
@hamedhsn please reopen if the issue still exists

/close

**Comment by hamedhsn** [comment]
UPDATE: the error is because at the moment AWS does not support kms enabled bucket with lustre fsx. We have tested it with bucket without kms and it works fine.

**Comment by chyz198** [comment]
Let us know if supporting KMS enabled bucket is a wanted feature.

**Comment by hamedhsn** [comment]
@chyz198 we really need that and it is the only reason that we never started using fsx. literally waiting for the support atm.

**Comment by shines1011000** [comment]
@chyz198 can re-opened? I'm also not able to read data from files when the bucket is encrypted with a CMK. I confirmed that the driver works as expected as long as the bucket use a non CMK key. That's no ideal for us though because we have compliance reqs that require us to use customer managed keys.

**Comment by shines1011000** [comment]
@chyz198 yup, that's what support had me try but it's just not working for me. Do you happen to have any contacts who are using this driver in production? @hamedhsn did you ever get this working with a KMS bucket? @leakingtapan same question for you?
