### ISSUE TITLE
flock mountoption

### ISSUE THREAD

**Issue by tsigalko2003** [kubernetes-sigs/aws-fsx-csi-driver#65]
We are running some bioinformatic pipeline with NextFlow, which requires file lock when creating the local database to manage the subprocesses.  It requires mountoptions flock, or localflock enabled. Unfortunately, I got the error message saying the mountoption is not 
supported.

**Comment by leakingtapan** [comment]
Related to #30

**Comment by tsigalko2003** [comment]
Totally understand the volume of work it may need. Really appreciate if we can get flock/flocallock as your earliest convenience.  Nextflow can not work without file lock at the current stage.
