### ISSUE TITLE
Implement s3 export in CSI

### ISSUE THREAD

**Issue by tigerwings** [kubernetes-sigs/aws-fsx-csi-driver#67]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like in detail**
The current S3 export requires users to run a container in privileged mode with ```CAP_SYS_ADMIN``` capability. It's insecure to expose this permission to the end user for the export purpose.

**Describe alternatives you've considered**
This functionality should be handled by CSI driver if s3Export is specified in storageclass. 

**Additional context**
No

**Comment by leakingtapan** [comment]
Could you add more details on how do you think this driver should handle the s3export?

**Comment by tigerwings** [comment]
I didn't read the code and thought the [import counterpart](https://docs.aws.amazon.com/fsx/latest/LustreGuide/fsx-data-repositories.html#import-data-repository) has been implement so the export functionality implementation could be similar. 

It looks like the import (hsm_restore) is not there yet neither. 

What I can think now is that to run hsm_restore after the volume is created, and hsm_archive periodically in the driver and before the volume is deleted.

**Comment by wongma7** [comment]
I see your point about not wanting to give permission to run privileged pods to everybody who wants to use fsx. hsm_restore and hsm_archive at mount and unmount time make sense to me. But my understanding is that when/if to run these things is workload specific, plus s3 requests are cheap but not free, so it'd probably need to be configurable.

**Comment by tigerwings** [comment]
absolutely
> 
> 
> so it'd probably need to be configurable.

**Comment by fabboe** [comment]
In addition to the permissions, the container requires the Lustre client, which for most [distributions](https://downloads.whamcloud.com/public/lustre/latest-2.10-release/) is only achievable via installing deb files in the Docker IMHO.

**Comment by leakingtapan** [comment]
@tigerwings This is new feature you could explore for exporting data back to s3 using FSx for lustre native feature: https://aws.amazon.com/blogs/storage/new-enhancements-for-moving-data-between-amazon-fsx-for-lustre-and-amazon-s3/
