### ISSUE TITLE
Availability zone topology awareness

### ISSUE THREAD

**Issue by wongma7** [kubernetes-sigs/aws-fsx-csi-driver#72]
**Is your feature request related to a problem? Please describe.**
FSx file systems reside in 1 zone. They can be accessed from other AZs in the region but then that incurs data transfers charges.

From the FSx for Lustre creation page: "For best performance with your file system, access it from compute instances within the Availability Zone that it resides in. “Accessing your file system from other Availability Zones also incurs data transfer charges. For more information, see Data Transfer on the Amazon EC2 Pricing page."

**Describe the solution you'd like in detail**
By default, CreateVolume should create PVs with a node affinity matching the zone (based on the subnet in the StorageClass) the file system is created in.

**Describe alternatives you've considered**
Dynamic provisioning would still work without this change but this would be a good improvement.

**Additional context**

**Comment by wongma7** [comment]
Reference for how to do it so CSI topology ends up in kubernetes PV somewhere: https://kubernetes-csi.github.io/docs/topology.html

**Comment by leakingtapan** [comment]
Since `subnetId` in storage class serves the same purpose as `allowedTopologies` in [storageclass](https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies), we need to which one is preferred over the other and how this works with node services `NodeGetInfo` for topology

**Comment by wongma7** [comment]
Right. So allowedTopologies is a way to set accessibility_requirements in a CreateVolumeRequest https://github.com/kubernetes-csi/external-provisioner#topology-support to restrict where volumes can be provisioned. But for FSx, the provisioner is already (loosely) restricted to one topology/zone via subnetId, so it's not clear how to reconcile subnetId and allowedTopologies. The provisioner is not *strictly* restricted to subnetId's zone, because technically its volumes can be accessed in any topology/zone, just at a higher cost.

What if we simply propagated accessibility_requirements in the request to accessible_topology in the response? For example, if the user doesn't want to deal with cross-AZ traffic then they would set allowedTopologies to zone A to match the subnetId's zone, so the PV ends up with a node affinity for zone A. If they don't mind, they can leave allowedTopologies blank. If they set it to something else, we could either error or treat it as blank.

For reference, the FSx UI expects you to first explicitly select a zone then select a subnetId from the zone. Obviously we can't achieve that UX via StorageClass yaml...
