### ISSUE TITLE
fsx-csi-controller-0 stuck in crashloopback after upgrade to CSI 1.0 on master and downgrade to v0.1.0 with kiam

### ISSUE THREAD

**Issue by benoitbayol** [kubernetes-sigs/aws-fsx-csi-driver#77]
/kind bug

**What happened?**
I was on the master tag and my cluster upgraded to the version of this week-end with the modification for CSI 1.0 (for k8s 1.14)

I downgraded to v0.1.0 (I have k8s 1.13) by adding right annotations for kiam in the node.yaml and controller.yaml (not using secret.yaml since kiam is here)

I cannot get the controller working again. I have a log on fsx-plugin that says: 
 could not get metadata from AWS: EC2 instance metadata is not available

**What you expected to happen?**
Running state on everything

**How to reproduce it (as minimally and precisely as possible)?**
see upper

**Anything else we need to know?**:
Not sure if it is driver related or kiam related :/

**Environment**
- Kubernetes version (use `kubectl version`): 1.13
- Driver version: v0.1.0

**Comment by leakingtapan** [comment]
It failed [here](https://github.com/kubernetes-sigs/aws-fsx-csi-driver/blob/master/pkg/cloud/metadata.go#L63) when trying to call metadata service.

What's the driver manifest you are using? Is it the same as the one under deploy/kubernetes/manifest.yaml? Is this problem consistently happening or transient?

**Comment by benoitbayol** [comment]
I am using these files for deploy : https://github.com/kubernetes-sigs/aws-fsx-csi-driver/tree/v0.1.0/deploy/kubernetes

I edited them for removing the mapping of aws secret keys and added my annotations for kiam.

**Comment by benoitbayol** [comment]
Problem solved. 

It was coming from the kiam agent since the whilelist was not giving the authorisation to check for some apis in metadata that are used by the controller.

**Comment by leakingtapan** [comment]
Glad to hear.

/close

**Comment by vishalmaheswari** [comment]
> Problem solved.
> 
> It was coming from the kiam agent since the whilelist was not giving the authorisation to check for some apis in metadata that are used by the controller.

How was this issue solved? I am getting same error and got stuck..
