### ISSUE TITLE
How to install v0.1.0?

### ISSUE THREAD

**Issue by armandmcqueen** [kubernetes-sigs/aws-fsx-csi-driver#83]
Now that master branch no longer works on 1.13, is there a one-line way to install v0.1.0 of the driver? Similar to:

`kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-fsx-csi-driver/master/deploy/kubernetes/manifest.yaml`

**Comment by leakingtapan** [comment]
here is what you can do:
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-fsx-csi-driver/v0.1.0/deploy/kubernetes/controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-fsx-csi-driver/v0.1.0/deploy/kubernetes/node.yaml
```

The v0.1.0 manifest contains the driver image tag for v0.1.0 release.

**Comment by armandmcqueen** [comment]
Thanks, I didn't see the tag.

**Comment by jarednielsen** [comment]
I'm using AWS EKS 1.14, and FSx mounting fails with error message
```
Warning  FailedMount  1s (x5 over 9s)  kubelet, ip-{IP}.ec2.internal  MountVolume.MountDevice failed for volume "pv-fsx" : driver name fsx.csi.aws.com not found in the list of registered CSI drivers
```

after running `kubectl apply -k "github.com/kubernetes-sigs/aws-fsx-csi-driver/deploy/kubernetes/overlays/dev/?ref=master"`

However, if I switch to use 
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-fsx-csi-driver/v0.1.0/deploy/kubernetes/controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/aws-fsx-csi-driver/v0.1.0/deploy/kubernetes/node.yaml
```
as recommended for Kubernetes 1.13, then mounting works as expected. This seems to contradict the version support matrix given in the main README. Is this a bug on the EKS side or the fsx-csi-driver side?

**Comment by leakingtapan** [comment]
what's ur worker node version?

**Comment by jarednielsen** [comment]
v1.14.8-eks-b8860f
